schema_version = "1.0.0"
id = "dicomator"  # use lowercase unique id
version = "0.2.0"
name = "DICOMator"
tagline = "Converts mesh objects into DICOM CT files"
maintainer = "Michael Douglass"
type = "add-on"
website = "https://github.com/drmichaeldouglass/DICOMator"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["3D View", "Medical", "CT", "DICOM"]
copyright = ["2024 Michael Douglass"]
platforms = ["windows-x64"]
wheels = [
    "./wheels/scikit_image-0.24.0-cp311-cp311-win_amd64.whl",
    "./wheels/pydicom-2.3.1-py3-none-any.whl",
    "./wheels/scipy-1.14.1-cp311-cp311-win_amd64.whl"
]

# Required permissions for file operations
[permissions]
files = "Save DICOM files to disk"

