schema_version = "1.0.0"
id = "dicomator"  # use lowercase unique id
version = "3.1.1"
name = "DICOMator"
tagline = "Converts mesh objects into synthetic CT/MR series or camera-based DRRs"
maintainer = "Michael Douglass"
type = "add-on"
website = "https://github.com/drmichaeldouglass/DICOMator"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["3D View", "Medical", "CT", "DICOM"]
copyright = ["2024 Michael Douglass"]
platforms = ["windows-x64","macos-arm64"]
wheels = [
    "./wheels/pydicom-3.0.1-py3-none-any.whl"
]

# Required permissions for file operations
[permissions]
files = "Save DICOM files to disk"

